jackson:
  deserialization:
    ACCEPT_SINGLE_VALUE_AS_ARRAY: true
  serialization:
    FAIL_ON_EMPTY_BEANS: false

document:
  management:
    store:
      url: ${DOCUMENT_MANAGEMENT_STORE_URL:http://localhost:5006}

cohort: onlineSubmissionPrivateBeta

documentation:
  swagger:
    enabled: true

logging:
  level:
    org.springframework.web: ERROR
    uk.gov.hmcts.reform.divorce.casedataformatterservice: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

//TODO - this file should not exist at all